name: meshing_splats
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.13.3=h4a9f257_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9e=h5eee18b_3
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.6.13=h12debd9_1
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - readline=8.3=hc2a1206_0
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.6.0=py36
  - torchvision=0.7.0=py36_cu102
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - bitsandbytes==0.44.1
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.12
    - clang==5.0
    - cycler==0.11.0
    - dataclasses==0.8
    - decorator==4.4.2
    - embreex==2.17.7.post5
    - flatbuffers==1.12
    - future==1.0.0
    - gast==0.4.0
    - glfw==2.9.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.48.2
    - h5py==3.1.0
    - idna==3.10
    - imageio==2.15.0
    - imageio-ffmpeg==0.4.7
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lpips==0.1.4
    - markdown==3.3.7
    - matplotlib==3.3.4
    - networkx==2.5.1
    - nvdiffrast==0.3.3
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pillow==8.4.0
    - protobuf==3.19.6
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pyopengl==3.1.10
    - pyopengl-accelerate==3.1.10
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pywavelets==1.1.1
    - requests==2.27.1
    - requests-oauthlib==2.0.0
    - rsa==4.9.1
    - rtree==0.9.7
    - scikit-image==0.17.2
    - scipy==1.5.4
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.6.2
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - tqdm==4.64.1
    - trimesh==3.23.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.20
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.6.0
prefix: /home/geiger/gwb652/.conda/envs/nvdiffrast
